
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1104
      LINK : fatal error LNK1104: 无法打开文件“libcmt.lib”
      clang++: error: linker command failed with exit code 1104 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1243 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1243 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-5ygwzw"
      binary: "D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-5ygwzw"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-5ygwzw'
        
        Run Build Command(s): C:/Qt/Tools/CMake_64/bin/cmake.exe -E env VERBOSE=1 C:/Users/MagmaDimsum/mingw/mingw64/bin/mingw32-make.exe -f Makefile cmTC_bd3fe/fast
        C:/Users/MagmaDimsum/mingw/mingw64/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_bd3fe.dir\\build.make CMakeFiles/cmTC_bd3fe.dir/build
        mingw32-make[1]: Entering directory 'D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-5ygwzw'
        Building CXX object CMakeFiles/cmTC_bd3fe.dir/CMakeCXXCompilerABI.cpp.obj
        C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_bd3fe.dir/CMakeCXXCompilerABI.cpp.obj -MF CMakeFiles\\cmTC_bd3fe.dir\\CMakeCXXCompilerABI.cpp.obj.d -o CMakeFiles\\cmTC_bd3fe.dir\\CMakeCXXCompilerABI.cpp.obj -c C:\\Qt\\Tools\\CMake_64\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_bd3fe.exe
        C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E cmake_link_script CMakeFiles\\cmTC_bd3fe.dir\\link.txt --verbose=1
        C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd  -v -Xlinker /subsystem:console -fuse-ld=lld-link @CMakeFiles\\cmTC_bd3fe.dir\\objects1.rsp -o cmTC_bd3fe.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_bd3fe.lib -Xlinker /pdb:D:\\Code\\RM26\\custom_client\\rm_test\\cmake-mqtt-test\\CMakeFiles\\CMakeScratch\\TryCompile-5ygwzw\\cmTC_bd3fe.pdb -Xlinker /version:0.0 
        clang version 20.1.4
        Target: x86_64-pc-windows-msvc
        Thread model: posix
        InstalledDir: C:\\Program Files\\LLVM\\bin
         "C:\\\\Program Files\\\\LLVM\\\\bin\\\\lld-link" -out:cmTC_bd3fe.exe "-libpath:C:\\\\Program Files\\\\LLVM\\\\lib\\\\clang\\\\20\\\\lib\\\\windows" -nologo -debug /subsystem:console CMakeFiles/cmTC_bd3fe.dir/CMakeCXXCompilerABI.cpp.obj /MANIFEST:EMBED /implib:cmTC_bd3fe.lib "/pdb:D:\\\\Code\\\\RM26\\\\custom_client\\\\rm_test\\\\cmake-mqtt-test\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-5ygwzw\\\\cmTC_bd3fe.pdb" /version:0.0
        lld-link: error: could not open 'msvcrtd.lib': no such file or directory
        clang++: error: linker command failed with exit code 1 (use -v to see invocation)
        mingw32-make[1]: *** [CMakeFiles\\cmTC_bd3fe.dir\\build.make:100: cmTC_bd3fe.exe] Error 1
        mingw32-make[1]: Leaving directory 'D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-5ygwzw'
        mingw32-make: *** [Makefile:126: cmTC_bd3fe/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe"
    directories:
      source: "D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-fk6oei"
      binary: "D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-fk6oei"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-fk6oei'
        
        Run Build Command(s): C:/Qt/Tools/CMake_64/bin/cmake.exe -E env VERBOSE=1 C:/Users/MagmaDimsum/mingw/mingw64/bin/mingw32-make.exe -f Makefile cmTC_3b88f/fast
        C:/Users/MagmaDimsum/mingw/mingw64/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_3b88f.dir\\build.make CMakeFiles/cmTC_3b88f.dir/build
        mingw32-make[1]: Entering directory 'D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-fk6oei'
        Building CXX object CMakeFiles/cmTC_3b88f.dir/testCXXCompiler.cxx.obj
        C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_3b88f.dir/testCXXCompiler.cxx.obj -MF CMakeFiles\\cmTC_3b88f.dir\\testCXXCompiler.cxx.obj.d -o CMakeFiles\\cmTC_3b88f.dir\\testCXXCompiler.cxx.obj -c D:\\Code\\RM26\\custom_client\\rm_test\\cmake-mqtt-test\\CMakeFiles\\CMakeScratch\\TryCompile-fk6oei\\testCXXCompiler.cxx
        Linking CXX executable cmTC_3b88f.exe
        C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E cmake_link_script CMakeFiles\\cmTC_3b88f.dir\\link.txt --verbose=1
        C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:console -fuse-ld=lld-link @CMakeFiles\\cmTC_3b88f.dir\\objects1.rsp -o cmTC_3b88f.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_3b88f.lib -Xlinker /pdb:D:\\Code\\RM26\\custom_client\\rm_test\\cmake-mqtt-test\\CMakeFiles\\CMakeScratch\\TryCompile-fk6oei\\cmTC_3b88f.pdb -Xlinker /version:0.0  @CMakeFiles\\cmTC_3b88f.dir\\linkLibs.rsp
        lld-link: error: could not open 'kernel32.lib': no such file or directory
        lld-link: error: could not open 'user32.lib': no such file or directory
        lld-link: error: could not open 'gdi32.lib': no such file or directory
        lld-link: error: could not open 'winspool.lib': no such file or directory
        lld-link: error: could not open 'shell32.lib': no such file or directory
        lld-link: error: could not open 'ole32.lib': no such file or directory
        lld-link: error: could not open 'oleaut32.lib': no such file or directory
        lld-link: error: could not open 'uuid.lib': no such file or directory
        lld-link: error: could not open 'comdlg32.lib': no such file or directory
        lld-link: error: could not open 'advapi32.lib': no such file or directory
        lld-link: error: could not open 'oldnames.lib': no such file or directory
        lld-link: error: could not open 'msvcrtd.lib': no such file or directory
        clang++: error: linker command failed with exit code 1 (use -v to see invocation)
        mingw32-make[1]: *** [CMakeFiles\\cmTC_3b88f.dir\\build.make:101: cmTC_3b88f.exe] Error 1
        mingw32-make[1]: Leaving directory 'D:/Code/RM26/custom_client/rm_test/cmake-mqtt-test/CMakeFiles/CMakeScratch/TryCompile-fk6oei'
        mingw32-make: *** [Makefile:126: cmTC_3b88f/fast] Error 2
        
      exitCode: 2
...
